using System.Collections;
using System.Collections.Generic;
using UnityEngine;

namespace Vox3D.Engine
{ 
    public class World : MonoBehaviour
    {
        private string _ID;

        private Vox3DProperties _Properties;

        private Dictionary<Vector3, Chunk> _Chunks; // Dictionary holding chunks. Uses their world-space position as key, in order to easily reference them

        private HeightMap2D _HeightMap;             // Holds the map generated by a given noise source. The map acts as the lookup table for voxel elevation
        private HeightMap2D _MoistureMap;           // Holds the map generated by a given noise source. The map acts as the lookup table for the biome given by moisture

        public Dictionary<Vector3, Chunk> Chunks    { get => _Chunks; set => _Chunks = value; }
        public HeightMap2D HeightMap                { get => _HeightMap; set => _HeightMap = value; }
        public HeightMap2D MoistureMap              { get => _MoistureMap; set => _MoistureMap = value; }
        public Vox3DProperties Properties           { get => _Properties; set => _Properties = value; }
        public string ID                            { get => _ID; set => _ID = value; }

        /// <summary>
        /// Method used to set basic parameters for world and heightmap generation. 
        /// Initial parameters are obtained from the Vox3DProperties in the manager instance.
        /// </summary>
        /// <returns></returns>
        public void GenerateMaps()
        {
            Chunks      = new Dictionary<Vector3, Chunk>();

            // Set basic parameters for heightmap generation

            int width   = Properties.WorldSize * Properties.ChunkSize;
            int height  = Properties.WorldSize * Properties.ChunkSize;

            var hSource = Properties.HNoiseSource;
            HeightMap   = new HeightMap2D(width, height, 0.0f, hSource);
            HeightMap.Normalize();
            
            var mSource = Properties.MNoiseSource;
            MoistureMap = new HeightMap2D(width, height, 0.0f, mSource);
            MoistureMap.Normalize();

        }
        public void PopulateWorld()
        {

            if(Chunks.Count > 0)
            {
                Debug.LogWarning($"Chunk dictionary is not empty. Ensure dictionary is empty before calling PopulateChunks().");
                return;
            }

            for (int x = 0; x < Properties.WorldSize; x++)
            {
                for (int y = 0; y < Properties.WorldSize; y++)
                {
                    for (int z = 0; z < Properties.WorldSize; z++)
                    {
                        // Ensure that each chunk takes into account both the size of the chunks and the size of the voxels
                        int worldScale = Properties.ChunkSize * Properties.VoxelSize;

                        Vector3 chunkPosition   = new Vector3(x, y, z) * worldScale;
                        GameObject chunkObject  = new GameObject($"Chunk_{x}_{y}_{z}");

                        chunkObject.transform.position  = chunkPosition;
                        chunkObject.transform.parent    = this.transform;

                        Chunk chunk = chunkObject.AddComponent<Chunk>();

                        chunk.ParentWorld   = this;

                        chunk.MeshFilter    = chunkObject.AddComponent<MeshFilter>();
                        chunk.MeshRenderer  = chunkObject.AddComponent<MeshRenderer>();
                        chunk.MeshCollider  = chunkObject.AddComponent<MeshCollider>();

                        chunk.ChunkSize     = Properties.ChunkSize;
                        chunk.VoxelSize     = Properties.VoxelSize;
                        chunk.Voxels        = new Voxel[Properties.ChunkSize, Properties.ChunkSize, Properties.ChunkSize];

                        chunk.Vertices      = new List<Vector3>();
                        chunk.Indices       = new List<int>();
                        chunk.Uvs           = new List<Vector2>();
                        chunk.Colors        = new List<Color32>();

                        chunk.tag = "Chunk";

                        chunk.MeshRenderer.material = Properties.VoxelDefaultMaterial;

                        Chunks.Add(chunkPosition, chunk);

                    }
                }
            }

        }
        public void PopulateChunks()
        {
            foreach (KeyValuePair<Vector3, Chunk> pair in Chunks)
            {
                PriorityCallStack.Instance().Push(() => {
                    if (Chunks.ContainsKey(pair.Key)) pair.Value.PopulateChunk();
                }, 0);
            }
        }
        public void GenerateGeometry()
        {
            foreach (KeyValuePair<Vector3, Chunk> pair in Chunks)
            {
                PriorityCallStack.Instance().Push(() => {
                    if (Chunks.ContainsKey(pair.Key)) pair.Value.GenerateGeometry_Greedy();
                }, 0);
            }

        }
        public void PurgeWorld()
        {
            foreach (KeyValuePair<Vector3, Chunk> pair in Chunks)
            {
                pair.Value.PurgeChunk();
                Destroy(pair.Value.gameObject);
            }

            Chunks.Clear();
        }

        /// <summary>
        /// Checks whether point is within a chunk.
        /// If it is, the chunk is returned.
        /// </summary>
        /// <param name="point">point in world space</param>
        /// <returns></returns>
        public Chunk GetChunkAt(Vector3 point)
        {

            if(Chunks.Count == 0)
            {
                Debug.LogWarning($"Chunks dictionary was empty for world {name}. Ensure dictionary is populated before calling GetChunkAt().");
                return null;
            }

            // Calculate the chunk's precise position by eliminating floating point values
            Vector3Int chunkCoordinates = new Vector3Int(
                Mathf.FloorToInt(point.x / (Properties.ChunkSize * Properties.VoxelSize)) * (Properties.ChunkSize * Properties.VoxelSize),
                Mathf.FloorToInt(point.y / (Properties.ChunkSize * Properties.VoxelSize)) * (Properties.ChunkSize * Properties.VoxelSize),
                Mathf.FloorToInt(point.z / (Properties.ChunkSize * Properties.VoxelSize)) * (Properties.ChunkSize * Properties.VoxelSize)
            );

            // Retrieve and return the chunk at the calculated position within the dictionary
            if (Chunks.TryGetValue(chunkCoordinates, out Chunk chunk))
            {
                return chunk;
            }

            // Return null if no chunk exists at the position
            return null;
        }

        public void DeleteChunk(Vector3 position)
        {
            Chunks.Remove(position);
            Chunks.TryGetValue(position, out Chunk chunk);
            if(chunk is not null) 
                Destroy(chunk.gameObject);
        }

        public void DeleteChunk(Chunk chunk)
        {
            foreach(var pair in Chunks)
            {
                if (pair.Value.GetInstanceID() == chunk.GetInstanceID())
                {
                    Chunks.Remove(pair.Key);
                    Destroy(pair.Value.gameObject);
                    break;
                }
            }
        }

    }

}
